site_name: SilverLingua
site_description: A framework for building AI agents
repo_url: https://github.com/DeathRight/SilverLingua
repo_name: DeathRight/SilverLingua

theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - navigation.top
    - toc.follow
    - content.code.copy
  custom_dir: docs/stylesheets

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: ["src"]
          import:
            - https://docs.python.org/3/objects.inv
          options:
            show_source: true
            show_root_heading: true
            show_root_toc_entry: true
            show_root_full_path: false
            heading_level: 1
            docstring_style: google
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            separate_signature: true
            show_signature_annotations: true
            signature_crossrefs: true
            line_length: 10
            members_order: source
            show_if_no_docstring: true
            filters: ["^[^_]|^_[^_]"]
            merge_init_into_class: true
            docstring_style: google
            inherited_members: true

nav:
  - Home: index.md
  - Getting Started:
      - Installation: getting-started/installation.md
      - Quickstart: getting-started/quickstart.md
  - API Reference:
      - SilverLingua:
        - config: api/config.md
        - core:
          - atoms:
            - index: api/core/atoms/index.md
            - Memory: api/core/atoms/memory.md
            - Prompt: api/core/atoms/prompt.md
            - Role: api/core/atoms/role.md
            - Tokenizer: api/core/atoms/tokenizer.md
            - Tool: api/core/atoms/tool.md
          - molecules:
            - index: api/core/molecules/index.md
            - Link: api/core/molecules/link.md
            - Notion: api/core/molecules/notion.md
          - organisms:
            - index: api/core/organisms/index.md
            - Idearium: api/core/organisms/idearium.md
          - templates:
            - index: api/core/templates/index.md
            - Agent: api/core/templates/agent.md
            - Model: api/core/templates/model.md
        - Modules:
            - OpenAI: api/modules/openai.md
            - Anthropic: api/modules/anthropic.md

markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 3
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.superfences
  - pymdownx.inlinehilite

watch:
  - src/SilverLingua

extra_css:
  - stylesheets/extra.css
